### ISSUE TITLE
Include pipeline_interface.yaml files?

### ISSUE THREAD

**Issue by aaron-gu** [pepkit/example_peps#1]
Since these example peps are linked from looper (https://github.com/pepkit/looper), would it be a good idea to include pipeline_interface.yaml files with each example, so that looper can be run?

**Comment by nsheff** [comment]
these examples are more universal... it doesn't really include pipelines.

this repository includes both a PEP and a looper pipeline: https://github.com/pepkit/hello_looper

This gets a bit tricky... maybe it's best to just remove that link from the looper readme.

**Comment by nsheff** [comment]
I've changed things around, let me know what you think now. look at the readme in looper and see if it is more clear.

**Comment by aaron-gu** [comment]
The changes all around are great

**Comment by nsheff** [comment]
ok, closing issue!
